version: '3.5'

services:

  mailhost:
   image: phplist/postfix:latest
   restart: always
   volumes:
     - mailhost_spool:/var/spool/postfix

  phplist:
    depends_on:
     - db
     - mailhost
     - smtp
    image: phplist/phplist:latest
    volumes:
     - images:/var/www/phpList3/public_html/images
     - ./config/config.php:/var/www/phpList3/public_html/lists/config/config.php:z
    ports:
     - "8080:80"
    restart: always
    environment:
      DB_HOST: db
      DB_USER: phplist
      DB_PASSWORD: phplist
      DB_NAME: phplist
      MAILHOST: smtp
      ADMIN_NAME: admin
      ADMIN_PASSWORD: password
      ADMIN_EMAIL: diegogullo@gmail.com
      HOSTNAME: localhost
      PORT: 8080

  db:
    image: mysql:5.7
    command: [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    restart: always
    ports:
      - "3334:3306"
    environment:
      MYSQL_ROOT_PASSWORD: phplist
      MYSQL_DATABASE: phplist
      MYSQL_USER: phplist
      MYSQL_PASSWORD: phplist
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf

  smtp:
    image: tophfr/mailcatcher
    ports:
      - "1080:80"
      - "1025:25"
volumes:
    images:
    mailhost_spool:
    mysqldata:
